export enum ACTION_NOTIF {
  STORE = "ACTION_NOTIF.STORE",
  STOP_LOADING = "ACTION_NOTIF.STOP_LOADING",
  MARK_READ_ITEM = "ACTION_NOTIF.MARK_READ_ITEM",
  MARK_READ_ALL = "ACTION_NOTIF.MARK_READ_ALL",
}
