export enum ACTION_AUTH {
  LOGIN = "ACTION_AUTH.LOGIN",
  LOGOUT = "ACTION_AUTH.LOGOUT",
  UPDATE_NAME = "ACTION_AUTH.UPDATE_NAME",
  UPDATE_PHOTO = "ACTION_AUTH.UPDATE_PHOTO",
  UPDATE_EMAIL_VERIFIED = "ACTION_AUTH.UPDATE_EMAIL_VERIFIED",
}
