export enum ACTION_CART {
  STORE = "ACTION_CART.STORE",
  STOP_LOADING = "ACTION_CART.STOP_LOADING",
  ADD_ITEM = "ACTION_CART.ADD_ITEM",
  REMOVE_ITEM = "ACTION_CART.REMOVE_ITEM",
  CHECKOUT_CART = "ACTION_CART.CHECKOUT_CART",
}
