export enum ACTION_COURSES {
  STORE = "ACTION_COURSES.STORE",
  STORE_OWNED = "ACTION_COURSES.STORE_OWNED",
  STOP_LOADING = "ACTION_COURSES.STOP_LOADING",
  STOP_LOADING_OWNED = "ACTION_COURSES.STOP_LOADING_OWNED",
  TOGGLE_WISHLIST = "ACTION_COURSES.TOGGLE_WISHLIST",
  UPDATE_LEARN = "ACTION_COURSES.UPDATE_LEARN",
}
