export enum TPayment {
  PAID = "PAID",
  PENDING = "PENDING",
}

export enum ACTION_PAYMENTS {
  STORE = "ACTION_PAYMENTS.STORE",
  STOP_LOADING = "ACTION_PAYMENTS.STOP_LOADING",
  ADD_ITEM = "ACTION_PAYMENTS.ADD_ITEM",
  REMOVE_ITEM = "ACTION_PAYMENTS.REMOVE_ITEM",
}
