export enum ACTION_WISHLIST {
  STORE = "ACTION_WISHLIST.STORE",
  STOP_LOADING = "ACTION_WISHLIST.STOP_LOADING",
  ADD_ITEM = "ACTION_WISHLIST.ADD_ITEM",
  REMOVE_ITEM = "ACTION_WISHLIST.REMOVE_ITEM",
}
